import 'dotenv/config';
import express from 'express'; import helmet from 'helmet'; import cors from 'cors'; import rateLimit from 'express-rate-limit'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import {z} from 'zod';
import {pool} from './db.js'; import {auth} from './middleware/auth.js'; import {cartFor} from './services/cart.js';
const app=express(), port=process.env.PORT||4000;
app.use(helmet()); app.use(cors({origin:(process.env.CORS_ORIGIN||'http://localhost:5173').split(','),methods:['GET','POST','PATCH','DELETE']})); app.use(express.json({limit:'20kb'})); app.use(rateLimit({windowMs:15*60*1000,max:200,standardHeaders:true,legacyHeaders:false}));
const sign=u=>jwt.sign({sub:u.id,email:u.email,name:u.name},process.env.JWT_SECRET,{expiresIn:'2h'});
app.get('/api/health',(_,res)=>res.json({status:'ok',service:'carcast-api'}));
app.get('/api/products',async(_,res,next)=>{try{const {rows}=await pool.query('SELECT id,slug,name,category,price_cents as "priceCents",description,color,image_key as "imageKey",featured FROM products ORDER BY featured DESC,id');res.json(rows)}catch(e){next(e)}});
app.post('/api/auth/register',async(req,res,next)=>{try{const v=z.object({name:z.string().trim().min(2).max(80),email:z.string().trim().email().max(255),password:z.string().min(8).max(128)}).parse(req.body);const hash=await bcrypt.hash(v.password,12);const {rows}=await pool.query('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email',[v.name,v.email.toLowerCase(),hash]);res.status(201).json({token:sign(rows[0]),user:rows[0]})}catch(e){if(e.code==='23505')return res.status(409).json({error:'An account with that email already exists.'});next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const v=z.object({email:z.string().email(),password:z.string().min(1).max(128)}).parse(req.body);const {rows}=await pool.query('SELECT id,name,email,password_hash FROM users WHERE email=$1',[v.email.toLowerCase()]);if(!rows[0]||!(await bcrypt.compare(v.password,rows[0].password_hash)))return res.status(401).json({error:'Incorrect email or password.'});const {password_hash,...user}=rows[0];res.json({token:sign(user),user})}catch(e){next(e)}});
app.post('/api/chat',async(req,res,next)=>{try{const v=z.object({question:z.string().trim().min(1).max(400)}).parse(req.body);const response=await fetch(`${process.env.RAG_URL||'http://rag:8001'}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(v),signal:AbortSignal.timeout(125000)});const data=await response.json();res.status(response.ok?200:503).json({answer:data.answer||"I don't have information about that."})}catch(e){if(e instanceof z.ZodError)return res.status(400).json({error:'Enter a short product question.'});console.error('Chat proxy:',e.message);res.status(503).json({answer:"I don't have information about that."})}});
app.get('/api/cart',auth,async(req,res,next)=>{try{res.json(await cartFor(req.user.sub))}catch(e){next(e)}});
app.post('/api/cart',auth,async(req,res,next)=>{try{const v=z.object({productId:z.number().int().positive(),quantity:z.number().int().min(1).max(20)}).parse(req.body);const {rows}=await pool.query('SELECT id FROM carts WHERE user_id=$1',[req.user.sub]);let id=rows[0]?.id;if(!id){id=(await pool.query('INSERT INTO carts(user_id) VALUES($1) RETURNING id',[req.user.sub])).rows[0].id}await pool.query('INSERT INTO cart_items(cart_id,product_id,quantity) VALUES($1,$2,$3) ON CONFLICT(cart_id,product_id) DO UPDATE SET quantity=LEAST(cart_items.quantity+$3,20)',[id,v.productId,v.quantity]);res.json(await cartFor(req.user.sub))}catch(e){next(e)}});
app.patch('/api/cart/:productId',auth,async(req,res,next)=>{try{const q=z.object({quantity:z.number().int().min(0).max(20)}).parse(req.body).quantity;const id=Number(req.params.productId);const {rows}=await pool.query('SELECT id FROM carts WHERE user_id=$1',[req.user.sub]);if(rows[0]){if(q===0) await pool.query('DELETE FROM cart_items WHERE cart_id=$1 AND product_id=$2',[rows[0].id,id]);else await pool.query('UPDATE cart_items SET quantity=$1 WHERE cart_id=$2 AND product_id=$3',[q,rows[0].id,id])}res.json(await cartFor(req.user.sub))}catch(e){next(e)}});
app.post('/api/checkout',auth,async(req,res,next)=>{const client=await pool.connect();try{const v=z.object({shippingName:z.string().trim().min(2).max(80),address:z.string().trim().min(8).max(250)}).parse(req.body);await client.query('BEGIN');const items=await cartFor(req.user.sub);if(!items.length){await client.query('ROLLBACK');return res.status(400).json({error:'Your cart is empty.'})}const total=items.reduce((s,x)=>s+x.priceCents*x.quantity,0);const invoice=`CC-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;const order=(await client.query('INSERT INTO orders(user_id,invoice_no,total_cents) VALUES($1,$2,$3) RETURNING id,invoice_no as "invoiceNo",total_cents as "totalCents",created_at as "createdAt"',[req.user.sub,invoice,total])).rows[0];for(const x of items)await client.query('INSERT INTO order_items(order_id,product_id,name,quantity,unit_price_cents) VALUES($1,$2,$3,$4,$5)',[order.id,x.productId,x.name,x.quantity,x.priceCents]);await client.query('DELETE FROM cart_items WHERE cart_id=(SELECT id FROM carts WHERE user_id=$1)',[req.user.sub]);await client.query('COMMIT');res.status(201).json({...order,items,shippingName:v.shippingName,address:v.address})}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
app.use((err,req,res,next)=>{if(err instanceof z.ZodError)return res.status(400).json({error:'Please check the details you entered.'});console.error(err);res.status(500).json({error:'Something went wrong. Please try again.'})});
async function ensureExpandedCatalog(){
 const values=[['blush-beetle','Blush Beetle','Cars',1799,'A curvy little city car in a soft pink finish, made for slow Sunday drives.','Blush','racer',false],['forest-4x4','Forest 4×4','Cars',2799,'A sturdy off-road miniature with an explorer spirit and chunky wheels.','Sage','rally',true],['coastal-cabriolet','Coastal Cabriolet','Cars',2399,'Top-down cruising in a breezy seafoam colourway.','Seafoam','gt',false],['golden-delivery','Golden Delivery','Trucks',1899,'A sunny delivery van for parcels, picnics and pretend play.','Golden','truck',false],['moon-rover','Moon Rover','Toys',2899,'A friendly lunar explorer toy, ready for crater-sized adventures.','Lavender','space',true],['garage-day-set','Garage Day Set','Sets',3699,'A playful workshop set with miniature details for a full pit-stop scene.','Terracotta','pit',false]];
 for(const p of values) await pool.query('INSERT INTO products(slug,name,category,price_cents,description,color,image_key,featured) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(slug) DO NOTHING',p);
}
ensureExpandedCatalog().catch(e=>console.error('Catalog seed skipped:',e.message)).finally(()=>app.listen(port,()=>console.log(`CarCast API on ${port}`)));
